---
- name: Ensure zsh with dependencies are installed.
  package:
    name: "{{ [ 'zsh' ] + zsh_dependencies }}"
    state: present
  become: true

- name: Get zsh installed path.
  shell: "command -v zsh"
  register: zsh_installed_path
  changed_when: false
