---
- name: Ensure zsh with dependencies are installed.
  ansible.builtin.package:
    name: "{{ ['zsh'] + zsh_dependencies }}"
    state: present
  become: true
  tags:
    - zsh
    - dependencies

- name: Get zsh installed path.
  ansible.builtin.command: "-v zsh"
  register: zsh_installed_path
  changed_when: false
  tags:
    - zsh
    - shell

- name: Create zsh config from template.
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.filepath }}"
    mode: "{{ zsh_config_mode }}"
    backup: "{{ zsh_config_backup }}"
    force: "{{ zsh_config_overwrite }}"
  become: true
  loop: "{{ zsh_system_config }}"
  tags:
    - zsh
    - config
