---
- name: Set user shell to zsh.
  user:
    name: "{{ zsh_user }}"
    shell: "{{ zsh_installed_path.stdout }}"
  become: true

- name: Create .zshrc from template.
  template:
    src: "{{ zsh_config_template }}"
    dest: "{{ zsh_config_dest }}"
    owner: "{{ zsh_user }}"
    backup: "{{ zsh_config_backup }}"
    force: "{{ zsh_config_overwrite }}"
  become: true
  become_user: "{{ zsh_user }}"
  when:
    - zsh_use_config == true
