---
#
# Extra file for the molecule verify step.
#
- name: Get stats of a zsh file
  ansible.builtin.stat:
    path: "{{ file_to_check }}"
    checksum_algorithm: sha1
  register: file_info

- name: File assertion
  ansible.builtin.assert:
    that:
      - file_info is defined
      - file_info.stat is defined
      - file_info.stat.exists == true
      - file_info.stat.checksum == 4d60d8b73b0c8025aa6ca21c8ee39298a5e62861
    fail_msg: An error occurred while distributing a zsh file.
