---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
provisioner:
  name: ansible
verifier:
  name: ansible
